#!/bin/bash

# ----- help  ----
if [ $1 = -h ]
then
    echo "SETUP:"
    echo "./prm get-ext     : download beam and noise files";
    echo "./prm setup-pilot : prepare Geant4 app for AMBER PRM pilot run"
    echo ""
    echo "BUILD:"
    echo "./prm build       : build Geant4 project (run under g4-mc env)";
    echo ""
    echo "RUN:"
    echo "./prm run         : run all four runners (beam, initial and scattered muons, recoil)";
    echo "./prm run-muon    : run only initial and scattered muons";
    echo "./prm run-proton  : run only recoil";
    echo "./prm run-noise   : generate noise events";
    echo "./prm run-all     : run Geant4 app and noise app";
    echo ""
    echo "CLEAN:"
    echo "./prm clean       : clean build, run and output directories";
    echo "./prm clean-ext   : remove all externals";
    echo "./prm clean-all   : try to refresh as much as possible";
fi

if [ $1 = --help ]
then
    ./prm -h;
fi

# ----- download noise dump file cmd ----
if [ $1 = get-ext ]
then
    cd external
    rm -rf beam noise;
    mkdir beam noise;
    cd noise;
    wget http://adzyuba.web.cern.ch/adzyuba/d/dump.txt;
    cd ../beam;
    wget http://adzyuba.web.cern.ch/adzyuba/d/beamfile_prm_mu100.root
    cd ../../;
fi

# ----- setup pilot ----
if [ $1 = setup-pilot ]
then
    source control/setup_pilot.sh;
fi



# ----- build cmd ----
if [ $1 = build ]
then
    source control/build_g4.sh;
fi

# ----- run-all -----
if [ $1 = run-all ]
then
    source control/run_beam.sh;
    source control/run_init.sh;
    source control/run_scat.sh;
    source control/run_prot.sh;
fi

# ----- run-muon ----
if [ $1 = run-muon ]
then
    source control/run_init.sh;
    source control/run_scat.sh;
fi

# ----- run-proton ----
if [ $1 = run-proton ]
then
    source control/run_prot.sh;
fi

# ----- download noise dump file cmd ----
if [ $1 = run-noise ]
then
    source control/run_noise.sh
fi

# ----- clean cmd ----
if [ $1 = clean ]
then
    source control/clean.sh;
fi

# ----- clean cmd ----
if [ $1 = clean-ext ]
then
    rm -rf external/beam external/noise;
#    rm external/esepp/*root;
#    rm external/esepp/*info;
fi

# ----- clean cmd ----
if [ $1 = clean-all ]
then
    ./prm clean
    ./prm clean-ext;
    rm -rf external/esepp*;
fi
