cd output;
cp -v ../code/reco/reco_tpc2.C .;
root -b reco_tpc2.C+;
mv FADC.root all/;
mv signal.data all/;
mv reco_tpc2.C scripts_done/;
rm *.pcm *.d *.so;
rm -rf figs;
mkdir figs_tpc;
mv *png figs_tpc/;
cd ../;
