cd output/init/;
cp -v ../../build/exec_PRM ./;
echo "Starting init app";
./exec_PRM run.mac >> inLOG;
echo "Done! (see output/init/inLOG for details)";
echo "";
echo "Converting time";
cp -v ../../code/reco/convert_init.py ./;
python convert_init.py;
mv out.convert out.data;
cd ../../;
